src/components/icon/icon.css

This removes the use of two undocumented custom properties from the component styles.
- `--ion-icon-size-large`
- `--ion-icon-size-small`

fix: remove unused size custom properties

---

package.json
src/components/global.ts

Currently, the `ionic-pwa-toolkit` starter fails to build (at least with `@stencil/core@1.3.0` but I think already before that) because of the `ionicons` dependency:
```
[ ERROR ]  Global Script: node_modules/ionicons/dist/collection/global.js
The code to be executed should be placed within a default function that is exported by the global script.
Ensure all of the code in the global script is wrapped in the function() that is exported.
```
To fix that, this PR:
- bumps Stencil to 1.3.0
- wraps the global script code in a function that is default exported
- fixes the build script order
For the last point, please check whether that's ok. The reason is that I wasn't able to build the project because the `icons` folder was missing until the `build.data` script had been run (which generates …

fix: default export a function in global script

---

src/components/icon/icon.css
src/components/icon/validate.ts
src/index.html

This PR fixes a regression in ionicons v5 where the inner SVG content of an ion-icon with a custom `src` does not get the proper styles applied due to a missing class. This results in a regression where setting the `font-size` on an `ion-icon` does not apply to ion-icons with a custom `src`.
In v4, we targeted the `svg` to apply proper styles. v5 targets `.ionicon` instead. Unfortunately, we only apply that class to the stock icons at build time, not to the custom icons that are loaded.
Example:
```
<ion-icon name="book" style="font-size: 50px;"></ion-icon>
<ion-icon src="./assets/bug_report.svg" style="font-size: 50px;"></ion-icon>
```
Expected Result: I would expect that the custom and standard icons are relatively the same size (around 50px)
Actual Result: The book icon grows in size, …

fix(icon): apply correct class to svg

---

src/components/icon/icon.tsx
src/index.html

The new chevron icons are not included in the logic needed to apply RTL.
Expected:
`chevron-forward-circle` points to the right on LTR and to the left on RTL.
Actual:
`chevron-forward-circle` points to the right on both LTR and RTL.

fix(icon): include chevron icons in flipRtl

---

src/data.json

The current terms stop after "log" or you have to type just "in" or "out"
This allows the searcher to narrow to login or logout specifically if
they want to.

fix(search): add login and logout search terms

---

src/components.d.ts
src/components/icon/icon.tsx

Follow-up [#869](https://github.com/ionic-team/ionicons/pull/869). In previous PR I added the doc "manually" to the readme.md instead of writing it down in the component.

fix: ariaHidden documentation source

---

readme.md

There is no such property as `stroke-weight`. Cheers!

docs: Use and refer to stroke-width everywhere

---

CHANGELOG.md

The v4 icon that showed multiple generic figures was called "contacts". The updated v5 analog would be "people" or "people-circle" (https://ionicons.com/usage#people-circle-outline). However the upgrade doc (https://github.com/ionic-team/ionicons/blob/master/CHANGELOG.md) incorrectly identifies  "person" - the singular figure icon - as the updated version of "contacts". This simple change corrects that.

fix multiple people icon update name

---

src/data.json

In Ionicons v4 the Earth icon was called globe. So it makes sense to add this as a tag.

chore: add tag "globe" to earth

---

package-lock.json
package.json
src/components/icon/icon.tsx
src/components/icon/test/icon.spec.ts

See also: https://github.com/ionic-team/ionic-framework/issues/23078
This PR fixes an issue where setting `aria-hidden="true"` would cause `flipRtl` to always equal `false` unless `this.flipRtl` was explicitly set. 
The reason this happened was `aria-hidden="true"` caused the component to not automatically generate an `aria-label`. We used this label to determine whether or not we should automatically flip the icon according to RTL mode. 
To fix this, I created a private variable that holds the icon name. We reference this icon to determine the state of `flipRtl`, and we also use this variable when auto generating an `aria-label`.

fix(): adding aria-hidden no longer disables automatic rtl switching

---

scripts/collection-copy.ts
stencil.config.ts

Stencil 1 had a deprecated loader that, when used, automatically added `module` and `nomodule` script tags to your web page. In Stencil 2 that loader was removed in favor of adding the `module` and `nomodule` script tags manually.
Ionicons v5.5 updated its internals to Stencil 2 to better support the custom elements bundle functionality, but in doing so we lost the deprecated loader.
This PR re-adds the deprecated loader, but it will be removed in Ionicons v6.0.
I will also be updating the Ionicons docs website with the new usage that Stencil 2 recommends.

fix(build): add old ionicons.js file 

---

package-lock.json
package.json

There was a change to the build process for stencil 2.10 that causes the compiled output to use less of the internal Stencil API. As a result, the latest version of Ionicons needs to be rebuilt as Stencil 2.10 is not backwards compatible with packages build with older versions of Stencil.

chore(): update ionicons to stencil 2.10

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/icon_request.yml
.github/ISSUE_TEMPLATE/incorrect_icon.yml

Adds templates for the following types:
- Bugs in the ion-icon component
- Feature requests for the ion-icon component
- Issues with the icon SVG data
- Icon requests

chore(github): add issue templates

---

.github/workflows/update-screenshots.yml

This job will not show up from https://github.com/ionic-team/ionicons/actions unless I first merge a file into `main`. This stub will allow me to test the actual implementation in a separate branch.

chore(ci): add update screenshots stub

---

scripts/collection-copy.ts
tsconfig.json
tsconfig.spec.json

Updates the `tsconfig.json` to exclude the `src/utils/test` infrastructure for Playwright from being copied into the collection output when performing a build. Also excludes the test svg assets from being copied into the collection output.

chore: exclude playwright test infra and test svg assets from collection output

---

scripts/bump-version.js

Vanilla JS files are git ignored, so the script file was never added.

chore(): add bump version script

---

.github/workflows/actions/publish-npm/action.yml
package.json

- The `--git-tag-version` flag was on the wrong command, so releases were getting tagged. This should not happen for dev builds.
- There was a `version` script causing the build to run twice (once when `npm version` was called then again with `npm run build`)

chore(ci): do not tag release for dev builds

---

.github/workflows/release.yml

This PR adds a stubbed implementation of the Ionicons release process so I can test in a branch.

chore(ci): add release CI stub

---

src/components/icon/icon.tsx
src/components/icon/test/icon.spec.ts

Currently, `ion-icon` will generate a default `aria-label` based on the icon name if no label is provided by the developer. However, this default label is often not useful as it doesn't give any info on the context the icon is being used in.
This PR removes the default `aria-label` logic as well as tests that pertained to it. Note that custom `aria-label`s are already handled by the `inheritAttributes` util.

fix(icon): remove auto-generated aria-label

---

src/components/icon/icon.tsx

resolves https://github.com/ionic-team/ionic-framework/issues/26712, resolves https://github.com/ionic-team/ionicons/issues/802
There is no watcher for the `ios` or `md` properties, so changing these values does not cause the rendered icon to be changed. Note: The `mode` property is not reactive in Ionic Framework, so I kept the behavior consistent here.

fix(icon): md and ios properties are reactive

---

src/components/icon/request.ts

The `DomParser` class is not available in a server context (only available in the browser). The previous changes were causing issues in SSR when trying to load an icon.
This PR removes the implementation of instantiating the `DomParser`, regardless of the environment. 
Resolves: https://github.com/ionic-team/ionicons/issues/1179

fix: DomParser usage in SSR

---

src/components/icon/test/utils.spec.ts
src/components/icon/utils.ts

See https://github.com/ionic-team/ionic-framework-design-documents/commit/a12daf314e9fdd6619503e88e9c99d2c184d95b7
This feature allows developers to pass icons to the icon map without explicitly setting the string name. This cuts down on boilerplate and reduces the likelihood of mapping the icon to a typo (i.e. `"log-ionic"` instead of `"logo-ionic"`)
For backwards compatibility purposes, the camel case key will still be available for developers who are explicitly mapping icon SVG data to camel case keys.
As part of this, Ionicons will now warn if multiple icons are mapped to the same key. TypeScript should prevent devs from explicitly doing this in Objects, but by autogenerating keys this may happen without the developer knowing. A warning will be logged so devs are aware of when this …

feat: allow passing in only icon SVG data to addIcons

---

src/data.json

Issue URL: N/A
There are no associated icons when searching for `fax`.
The `print` icon can also be used as a `fax` logo. When searching for the `fax` then the `print` icon will be provided.
Determined through this [icon request](https://github.com/ionic-team/ionicons/issues/1271#issuecomment-1710409700).

chore(print): add fax to tags

---

src/components/icon/icon.tsx

Issue URL: N/A
Icons won't load when using Angular binding.
Icons now load when using Angular binding.
N/A

fix(icon): verify the icon loads in the lifecycle

---

package-lock.json
package.json
stencil.config.ts

Resolves #1255
Upgrades the ionicons project to build with Stencil v4.

chore(deps): upgrade to stencil 4

---

src/components/icon/test/utils.spec.ts
src/components/icon/utils.ts

While working with Mike to test StarTrack, we discovered that mapping the same icon twice yields a warning when it should not.
**Example**
```typescript
addIcons({ logoIonic });
addIcons({ logoIonic });
```
This can happen in an application where same icon is used in multiple places. In that case it's necessary to call `addIcons` since we don't know which place will be loaded first. In this case, no warning should be logged since these are the same icon references.

fix(icon): mapping same icon does not warn

---

.github/workflows/release.yml

During the recent Ionicons 7.2.0 release the "finalize-release" step failed because the changelog had not been generated: https://github.com/ionic-team/ionicons/actions/runs/6470513416/job/17566942806
I noticed that Lerna 7 was being used which has several breaking changes that we are not accounting for (because we expect Lerna 6). This PR ensures that our release workflow only uses Lerna 6 (the local version). This is similar to https://github.com/ionic-team/ionic-framework/pull/27656

chore(ci): ensure local version of lerna is used

---

package-lock.json
src/components/icon/icon.css

Removes an unnecessary host-level style from `ion-icon` that conflicted with styling selectors in Ionic Framework. The icon will still scale dynamically with the font size of the container.

fix(icon): font scales without host style

---

src/components/icon/utils.ts

In https://github.com/ionic-team/ionic-framework/issues/28445 we received feedback that accidentally referring to an icon by name without first registering it is confusing because devs get a cryptic "invalid URL" error. This PR attempts to improve that experience by providing a more helpful message and giving developers steps they can take to fix the issue.
| `main` | branch |
| - | - |
| ![image](https://github.com/ionic-team/ionicons/assets/2721089/7d8bbf50-0ba6-4f2a-ac15-2a6f67e7834b) | ![image](https://github.com/ionic-team/ionicons/assets/2721089/864ee53d-8941-4d9a-a661-60afdc99a184) |
One note: This warning will be logged every time the icons tries to load. We currently load the icon in `connectedCallback` and `componentDidLoad`, so this warning can be logged twice on page load. In …

fix(icon): add better warning when loading icons

---

src/components/icon/test/utils.spec.ts
src/components/icon/utils.ts

resolves #1338
Do not contribute very often publicly, so any feedback regarding the pull request is welcome.
I know I jumped the gun by providing a pull request before the bug report has been validated.
I extended the existing test to cover the case with numbers. I keept the old test in place to avoid regression.
Unfortunately I can not link this pull request to my bug report: https://github.com/ionic-team/ionicons/issues/1338

fix(icon): icon names with numbers are correctly converted to kebab case

---

.github/CONTRIBUTING.md

The team has decided to not accept contributions that add or modify icon SVG assets. All SVG modifications are done by our in-house design team to ensure design consistency. This PR publicly documents our policy for this.

docs(contributing): clarify icon contributions

---

.github/ionic-issue-bot.yml

Like on the Ionic Framework repo, we'd like the opportunity to collect community feedback before potentially pursuing features. This adds an auto response for Ionitron when adding the community feedback label.

chore(ionitron): add auto response for community feedback

---

readme.md

In #1302 a user reported an issue experiencing issues loading Ionicons from a custom source. This patch adds a section on how to set a custom resource path through Stencil.
Note: the reported issue used a specific way to integrate ionicons via the `@ionic/angular/standalone` package. For folks just using an ionicon script tag as described in the readme, this won't be much useful. The added documentation requires the user to use a compiler that resolves the Ionicon and application code with the same resolver.
An alternative would be to add these docs to the `@ionic/angular` package, please advise!

fix(docs): add a section on custom svg paths

---

readme.md

Hi Ionicons team, 
While following the installation guide in the Readme, I noticed that the HTML code snippets for including the Ionicons loader via ESM CDN were not working as expected.
Based on ESM CDN [documentation](https://esm.sh/#docs), the standard URL syntax is typically:
```
https://esm.sh/PKG[@SEMVER][/PATH]
```
Hence, I have updated the URLs to move `/loader` pathname to the end, following the standard format.
https://esm.sh/ionicons@latest/loader
This correction appears to resolve the issue.

docs(readme): change incorrect module URLs

---

package.json
stencil.config.ts

The collections directory is used by consuming Stencil projects to append a project built with Stencil, to the build context of the current project using Stencil. It is weird, but means that for a project using Stencil (e.g.: Ionic Framework), to be able to build another project using Stencil (e.g.: Ionicons), it needs to be able to read in the generated collections metadata. I believe this mainly applies to the dist output target.
This was recently disabled/removed in the v8 work. This is the primary reason for the build error in: https://github.com/ionic-team/ionic-framework/pull/30390. 
There may be other ways to solve this problem. This is the primary way that I am aware resolves it.
Verification steps:
1. Clone the fork
2. Install dependencies: `npm install`
3. Build the project: …

fix: stencil projects can build ionicons
